[package]
name = "motoko-rts-tests"
version = "0.1.0"
authors = ["dfinity <sdk@dfinity.org"]
edition = "2018"

[dependencies]
maplit = "1.0.2"
motoko-rts = { path = "../motoko-rts/native" }
quickcheck = "0.9"
