[package]
name = "motoko-rts"
version = "0.1.0"
authors = ["dfinity <sdk@dfinity.org>"]
edition = "2018"

# For rlib use native/Cargo.toml
[lib]
crate-type = ["staticlib"]

[features]
default = ["panic_handler", "gc"]

# Enables garbage collector and bump allocator. Without this the GC module is
# disabled (not compiled) and allocation routines use `malloc`.
gc = []

# Defines a panic handler. Required for generating `staticlib` as static
# libraries need to be self-contained.
panic_handler = []

[dependencies]
libc = { version = "0.2.81", default_features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1 # makes debugging easier
opt-level = "s" # optimize for size
